batch_size          : 128
checkpoint_path     : ""
data_path           : /mnt/ex-ssd/Datasets/cifar10
dataset             : cifar10
device              : cuda
epochs              : 200
fraction            : 0.4
log_file            : ./train.log
log_level           : INFO
lr                  : 0.1
min_lr              : 0.0001
model               : resnet18
momentum            : 0.9
nesterov            : True
num_realizations    : 3
optimizer           : SGD
output_dir          : experiments/0322_1132
output_folder       : experiments
print_every         : 100
prune_epoch         : 10
prune_scheme        : grand
scheduler           : CosineAnnealingLR
seed                : 1002
test_interval       : 1
weight_decay        : 0.0005
workers             : 8